### ISSUE TITLE
I tried to force-close the app and it keeps bogging down my computer afterwards!

### ISSUE THREAD

**Issue by peterdsharpe** [Christophe-Foyer/Motor-Test-Stand-GUI#5]
To Reproduce: Try to close the app
System: Any

**Comment by Christophe-Foyer** [comment]
Wow, what an unexpected issue! If only I had documented this behavior in the readme!

The issue can probably be fixed if the child threads check for that the parent thread is alive and, if not, terminate the thread.

How's the motor test stand hardward going? Is it going to make it into the report? I really want some pitot tubes!

**Comment by Christophe-Foyer** [comment]
This is 100% a weird issue though. Not sure why the program is spawning separate subprocesses which aren't terminated on exit. I'll have to look into it.

**Comment by austinstover** [comment]
I thought that was because of the weird multithreading thing you were trying to do originally; since we revised the entire app I don't think this should be an issue.
