### ISSUE TITLE
Help! I'm not getting any graphs!

### ISSUE THREAD

**Issue by ghost** [Christophe-Foyer/Motor-Test-Stand-GUI#6]
I downloaded this repository, unzipped the app, and opened it, but it won't show me any graphs. Pls fix.

**Comment by Christophe-Foyer** [comment]
You ungrateful people D:

One of these days someone is going to look at these issue reports and go "what a rude developer!" haha.


But for the actual solution:
Did you plug in the arduino with sensors attached and the arduino code uploaded as instructed in the readme? If not please do that. You probably need to edit the arduino code to fit your use case but apart from that pretty easy.

**Comment by ghost** [comment]
Wait--I need an Arduino for this?

**Comment by Christophe-Foyer** [comment]
🤦
