### ISSUE TITLE
Program can't find SerialComm

### ISSUE THREAD

**Issue by austinstover** [Christophe-Foyer/Motor-Test-Stand-GUI#8]
So I finally forked the project, but every time I run the python teststand, I get the following error:

`Traceback (most recent call last):
  File "C:\Users\austi\Documents\Other\DBF\Motor-Test-Stand-GUI\source\Control Panel.py", line 36, in <module>
    from SerialComm.SerialComm import SerialComm
ImportError: No module named SerialComm.SerialComm`

@Christophe-Foyer Any idea why?

**Comment by Christophe-Foyer** [comment]
Do you have your serialcomm library included?

**Comment by Christophe-Foyer** [comment]
Also stop assigning issues to me haha

**Comment by austinstover** [comment]
All I did was fork the project, download it and run it. So yes, the library is included, and correctly too.

**Comment by Christophe-Foyer** [comment]
Try just importing serialcomm instead of serialcomm.serialcomm?

**Comment by austinstover** [comment]
Doing that throws an error.

**Comment by Christophe-Foyer** [comment]
Did you end up figuring out what the issue was?

**Comment by Christophe-Foyer** [comment]
Ok! This was a very dumb issue, you just need to add __init__.py to the folder so python can find the file. Not sure how it was working without it before but it's something you should know if you're gonna use python in any legit project
